### PR TITLE
cfg fix

### PR DESCRIPTION
**Pull request by newpavlov**
See rust-lang/libc#1422

### CODE REVIEW

**Comment by jD91mZM2** [comment]
Redox PRs go to https://gitlab.redox-os.org/.

**Comment by newpavlov** [comment]
It's not a Redox PR, but `libc` PR for Redox target...

@jackpot51
Can you copy this fix to your PR?

**Comment by jD91mZM2** [comment]
I didn't see the branch name, sorry. Hmm... I guess I don't really know where this PR should go. There is also [liblibc/redox-ci](https://gitlab.redox-os.org/redox-os/liblibc/tree/redox-ci) on GitLab, but I don't know which one is the mirror and which one is the real project.

**Comment by jackpot51** [comment]
This must go to https://gitlab.redox-os.org/redox-os/liblibc.git

This is just a mirror

**Pull request closed without merging**
